name: fortuneapp
description: "camon"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #state management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  #tarih format
  intl: ^0.19.0
  google_fonts: ^8.1.0

  #picker and animation
  image_picker: ^1.2.2
  lottie: ^3.1.2

  #network
  dio: ^5.6.0

  #storage
  shared_preferences: ^2.3.2
  firebase_core: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3

flutter:

  uses-material-design: true

  assets:
   - assets/animations/
   - assets/icon/
   - assets/tarot/
