name: fortuneapp
description: "camon"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ^3.12.1
  flutter: ">=3.44.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #state management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  #tarih format
  intl: ^0.19.0
  google_fonts: ^8.1.0

  #picker and animation
  image_picker: ^1.2.2
  lottie: ^3.1.2

  #network
  dio: ^5.6.0

  #storage
  shared_preferences: ^2.3.2
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^8.1.0
  go_router: ^17.2.3
  cloud_firestore: ^6.5.0
  connectivity_plus: ^7.1.1
  json_annotation: ">=4.11.0 <4.12.0"
  cloud_functions: ^6.3.2
  google_mobile_ads: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3
  json_serializable: ">=6.8.0 <6.13.2"

flutter:

  uses-material-design: true

  assets:
   - assets/animations/
   - assets/icon/
   - assets/tarot/
