// Burçların STATİK referans verisi (gezegen, element, tarih aralığı, motto).
// Skor ve commentDaily alanları fallback'tir; günlük değerler Firestore'daki
// `dailyHoroscopes/current` dokümanından gelir ve bunların üzerine yazılır.
const List<Map<String, dynamic>> zodiacReferenceData = [
  {
    'sign': 'aries',
    'planet': 'Mars',
    'element': 'Ateş',
    'dateRange': '21 Mart - 20 Nisan',
    'loveScore': 7,
    'healthScore': 7,
    'moneyScore': 6,
    'motto': 'Ben varım!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta enerjin yüksek; yeni girişimler için uygun.',
    'commentMonthly': 'Bu ay kariyer adımları öne çıkıyor.',
    'commentYearly': 'Bu yıl yeni başlangıçların yılı olabilir.',
  },
  {
    'sign': 'taurus',
    'planet': 'Venüs',
    'element': 'Toprak',
    'dateRange': '21 Nisan - 20 Mayıs',
    'loveScore': 8,
    'healthScore': 7,
    'moneyScore': 8,
    'motto': 'Sahip oluyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta maddi konularda istikrar var.',
    'commentMonthly': 'Bu ay ilişkilerin güçleniyor.',
    'commentYearly': 'Bu yıl finansal açıdan sağlamlaşırsın.',
  },
  {
    'sign': 'gemini',
    'planet': 'Merkür',
    'element': 'Hava',
    'dateRange': '21 Mayıs - 21 Haziran',
    'loveScore': 7,
    'healthScore': 6,
    'moneyScore': 7,
    'motto': 'Düşünüyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta iletişim ve fikir alışverişi öne çıkıyor.',
    'commentMonthly': 'Bu ay yeni bağlantılar kuruyorsun.',
    'commentYearly': 'Bu yıl öğrenme ve hareket yılı.',
  },
  {
    'sign': 'cancer',
    'planet': 'Ay',
    'element': 'Su',
    'dateRange': '22 Haziran - 22 Temmuz',
    'loveScore': 8,
    'healthScore': 7,
    'moneyScore': 6,
    'motto': 'Hissediyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta duygusal denge ve aile ön planda.',
    'commentMonthly': 'Bu ay yuva ve huzur konuları öne çıkıyor.',
    'commentYearly': 'Bu yıl içsel güvenini güçlendiriyorsun.',
  },
  {
    'sign': 'leo',
    'planet': 'Güneş',
    'element': 'Ateş',
    'dateRange': '23 Temmuz - 22 Ağustos',
    'loveScore': 8,
    'healthScore': 8,
    'moneyScore': 7,
    'motto': 'Yaratıyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta sahne senin; özgüvenin parlıyor.',
    'commentMonthly': 'Bu ay yaratıcılık ve görünürlük artıyor.',
    'commentYearly': 'Bu yıl liderlik fırsatları seni bekliyor.',
  },
  {
    'sign': 'virgo',
    'planet': 'Merkür',
    'element': 'Toprak',
    'dateRange': '23 Ağustos - 22 Eylül',
    'loveScore': 6,
    'healthScore': 8,
    'moneyScore': 7,
    'motto': 'Analiz ediyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta düzen ve planlama işine yarıyor.',
    'commentMonthly': 'Bu ay detaylar fark yaratıyor.',
    'commentYearly': 'Bu yıl emeklerin somut karşılık buluyor.',
  },
  {
    'sign': 'libra',
    'planet': 'Venüs',
    'element': 'Hava',
    'dateRange': '23 Eylül - 22 Ekim',
    'loveScore': 9,
    'healthScore': 6,
    'moneyScore': 7,
    'motto': 'Dengeliyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta ilişkilerde uyum ön planda.',
    'commentMonthly': 'Bu ay ortaklıklar güçleniyor.',
    'commentYearly': 'Bu yıl denge ve estetik temaların yılı.',
  },
  {
    'sign': 'scorpio',
    'planet': 'Plüton',
    'element': 'Su',
    'dateRange': '23 Ekim - 21 Kasım',
    'loveScore': 8,
    'healthScore': 7,
    'moneyScore': 8,
    'motto': 'Arzuluyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta sezgilerin güçlü; derine inebilirsin.',
    'commentMonthly': 'Bu ay dönüşüm ve yenilenme zamanı.',
    'commentYearly': 'Bu yıl güçlü bir içsel değişim yaşarsın.',
  },
  {
    'sign': 'sagittarius',
    'planet': 'Jüpiter',
    'element': 'Ateş',
    'dateRange': '22 Kasım - 21 Aralık',
    'loveScore': 7,
    'healthScore': 8,
    'moneyScore': 7,
    'motto': 'Keşfediyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta yeni ufuklar ve fırsatlar var.',
    'commentMonthly': 'Bu ay seyahat ve öğrenme öne çıkıyor.',
    'commentYearly': 'Bu yıl ufkun genişliyor.',
  },
  {
    'sign': 'capricorn',
    'planet': 'Satürn',
    'element': 'Toprak',
    'dateRange': '22 Aralık - 20 Ocak',
    'loveScore': 6,
    'healthScore': 7,
    'moneyScore': 9,
    'motto': 'Başarıyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta disiplin sonuç getiriyor.',
    'commentMonthly': 'Bu ay kariyer hedeflerin yükseliyor.',
    'commentYearly': 'Bu yıl emeklerinin meyvesini topluyorsun.',
  },
  {
    'sign': 'aquarius',
    'planet': 'Uranüs',
    'element': 'Hava',
    'dateRange': '21 Ocak - 18 Şubat',
    'loveScore': 7,
    'healthScore': 7,
    'moneyScore': 7,
    'motto': 'Özgürüm!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta özgün fikirlerin dikkat çekiyor.',
    'commentMonthly': 'Bu ay sosyal çevren genişliyor.',
    'commentYearly': 'Bu yıl yenilikçi adımların yılı.',
  },
  {
    'sign': 'pisces',
    'planet': 'Neptün',
    'element': 'Su',
    'dateRange': '19 Şubat - 20 Mart',
    'loveScore': 8,
    'healthScore': 6,
    'moneyScore': 6,
    'motto': 'İnanıyorum!',
    'commentYesterday': '',
    'commentDaily': 'Günlük burç yorumu hazırlanıyor...',
    'commentWeekly': 'Bu hafta sezgiler ve hayal gücü güçlü.',
    'commentMonthly': 'Bu ay ruhsal denge ön planda.',
    'commentYearly': 'Bu yıl içsel yolculuğun derinleşiyor.',
  },
];
